/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package tas.kagit.makas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;


/**
 *
 * @author AS
 */
public class game extends javax.swing.JFrame {
    public int us;
    public int ur = 0;
    public int pr= 0;
    public int ps;
    Random rand = new Random();
    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        tasButton = new javax.swing.JButton();
        kagitButton = new javax.swing.JButton();
        makasButton = new javax.swing.JButton();
        userImg = new javax.swing.JLabel();
        pcImg1 = new javax.swing.JLabel();
        skor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        users = new javax.swing.JLabel();
        pcs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(518, 432));
        setResizable(false);

        tasButton.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        tasButton.setText("TAŞ");
        tasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasButtonActionPerformed(evt);
            }
        });

        kagitButton.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        kagitButton.setText("KAĞIT");
        kagitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kagitButtonActionPerformed(evt);
            }
        });

        makasButton.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        makasButton.setText("MAKAS");
        makasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makasButtonActionPerformed(evt);
            }
        });

        skor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        skor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skor.setText("VS");

        jButton1.setText("Yeni Oyun");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        users.setFont(new java.awt.Font("Tahoma", 0, 200)); // NOI18N
        users.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        users.setText("0");
        users.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        pcs.setFont(new java.awt.Font("Tahoma", 0, 200)); // NOI18N
        pcs.setText("0");

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(159, 152, 152));
        jLabel1.setText("Hamdi Burak Dilek");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kagitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userImg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(skor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(pcImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(makasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcs, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pcs, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pcImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(skor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userImg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kagitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasButtonActionPerformed
        userImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/usertas.png")));
        us = 0;
        ps = rand.nextInt(3);
        if (ps == 0){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pctas.png")));
        }
        else if(ps == 1){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pckagit.png")));
            pr = pr+1;
        }
        else{
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pcmakas.png")));
            ur = ur + 1;
        }
        yeniEl();
        
// TODO add your handling code here:
    }//GEN-LAST:event_tasButtonActionPerformed
    
    private void kagitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kagitButtonActionPerformed
        userImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/userkagit.png")));
        ps = rand.nextInt(3);
        if (ps == 0){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pctas.png")));
            ur = ur+1;
        }
        else if(ps == 1){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pckagit.png")));
        }
        else{
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pcmakas.png")));
            pr = pr + 1;
        }
        yeniEl();
// TODO add your handling code here:
    }//GEN-LAST:event_kagitButtonActionPerformed
    
    private void makasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makasButtonActionPerformed
        userImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/usermakas.png")));
        ps = rand.nextInt(3);
        if (ps == 0){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pctas.png")));
            pr = pr+1;
        }
        else if(ps == 1){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pckagit.png")));
            ur = ur +1;
        }
        else{
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/normal/pcmakas.png")));
        }
        yeniEl();
// TODO add your handling code here:
    }//GEN-LAST:event_makasButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ur = 0;
        pr = 0;
        users.setText(ur+"");
        pcs.setText(pr+"");
        pcImg1.setIcon(null);
        userImg.setIcon(null);
        tasButton.setVisible(true);
        kagitButton.setVisible(true);
        makasButton.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
        public void yeniEl(){
        if(ur == 5){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/imoticons/youwin.png")));
            userImg.setIcon(null);
            tasButton.setVisible(false);
            kagitButton.setVisible(false);
            makasButton.setVisible(false);
            users.setText(ur+"");
        pcs.setText(pr+"");
            
            
            
        }
        else if(pr == 5){
            pcImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/imoticons/sad.png")));
            userImg.setIcon(null);
            tasButton.setVisible(false);
            kagitButton.setVisible(false);
            makasButton.setVisible(false);
           users.setText(ur+"");
        pcs.setText(pr+"");
            
            
        }
        else{
        users.setText(ur+"");
        pcs.setText(pr+"");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kagitButton;
    private java.awt.Label label1;
    private javax.swing.JButton makasButton;
    private javax.swing.JLabel pcImg1;
    private javax.swing.JLabel pcs;
    private javax.swing.JLabel skor;
    private javax.swing.JButton tasButton;
    private javax.swing.JLabel userImg;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
