/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package sinemabiletiotomasyunu;

import java.awt.List;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author AS
 */
public class AdminPaneli extends javax.swing.JFrame {
    private PreparedStatement preparedStatement = null, preparedStatement1 = null, preparedStatement2 ,
            preparedStatement3 = null, preparedStatement4 = null, preparedStatement5 = null, 
            preparedStatement6 = null, preparedStatement7 = null, preparedStatement8 = null, 
            preparedStatement9 = null, preparedStatement10 = null, preparedStatement11 = null,
            preparedStatement12 = null, preparedStatement13 = null, preparedStatement14 = null,
            preparedStatement15 = null, preparedStatement16 = null, preparedStatement17 = null;
    private ResultSet resultSet = null, resultSet1 = null, resultSet2 = null, resultSet3 = null,
            resultSet4 = null, resultSet6 = null, resultSet7 = null, resultSet8 = null, resultSet9 = null,
            resultSet11 = null, resultSet14 = null, resultSet15 = null, resultSet17 = null;
    int seansKontrolIndex = 0;
    int sen;
    int sboy;
    int snosil;
    String alfabe[] = {"A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","R","S","T","U","V","Y","Z"};
    ArrayList<String> seanslar = new ArrayList<>();
     ArrayList<String> filmler = new ArrayList<>();
    ArrayList<Integer> seansnolari = new ArrayList<>();
    ArrayList<Integer> eklenecekSeansNolari = new ArrayList<>();
    ArrayList[][] salonEnBoy;
    /**
     * Creates new form AdminPaneli
     */
    public void bilgileriGuncelle() throws SQLException{
        int bsi = 0;
        gsalon.removeAllItems();
        ssalon.removeAllItems();
        sFilmSil.removeAllItems();
        sseans.removeAllItems();
        seansnolari.clear();
        seanslar.clear();
        filmler.clear();
        seansek.removeAllItems();
        fsno.removeAllItems();
        preparedStatement2 = main.conn
                .prepareStatement("SELECT * from salon WHERE db = 0" );
        resultSet2 = preparedStatement2.executeQuery();
        
        while(resultSet2.next())
        {
            gsalon.addItem(resultSet2.getInt(1));
            ssalon.addItem(resultSet2.getInt(1));
        }
        
        preparedStatement6 = main.conn
                .prepareStatement("SELECT * from seans" );
        resultSet6 = preparedStatement6.executeQuery();
        while(resultSet6.next())
        {
            sseans.addItem(resultSet6.getString(1));
            seanslar.add(resultSet6.getString(1));
            seansnolari.add(resultSet6.getInt(2));
            seansek.addItem(resultSet6.getString(1));
        }
        preparedStatement8 = main.conn
                .prepareStatement("SELECT no from salon WHERE db = 0" );
        resultSet8 = preparedStatement8.executeQuery();
        while(resultSet8.next())
        {
            fsno.addItem(resultSet8.getInt(1));
                     
        }
        preparedStatement15 = main.conn
                .prepareStatement("SELECT isim from film" );
        resultSet15 = preparedStatement15.executeQuery();
        while(resultSet15.next())
        {
            sFilmSil.addItem(resultSet15.getString(1));
            filmler.add(resultSet15.getString(1));
        }
            
    }
    
    public AdminPaneli() {
      
        try {
            initComponents();
            bilgileriGuncelle();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPaneli.class.getName()).log(Level.SEVERE, null, ex);
            showMessageDialog(null, "Veri Tabanına Bağlantıda Bir Sorun Oluştu !");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        filmTab = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        alert2 = new javax.swing.JLabel();
        fismi = new javax.swing.JTextField();
        fsno = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filmKaydet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seansek = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        ekliseans = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bfiyati = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        filmSil = new javax.swing.JButton();
        sFilmSil = new javax.swing.JComboBox();
        seansTab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        seans_ekle = new javax.swing.JButton();
        seansText = new javax.swing.JLabel();
        seans_saati = new javax.swing.JSpinner();
        alert1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        sseansText = new javax.swing.JLabel();
        seans_sil = new javax.swing.JButton();
        sseans = new javax.swing.JComboBox();
        salonTab = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        kaydet = new javax.swing.JButton();
        boyText = new javax.swing.JLabel();
        boy = new javax.swing.JSpinner();
        enText = new javax.swing.JLabel();
        en = new javax.swing.JSpinner();
        snText = new javax.swing.JLabel();
        sn = new javax.swing.JSpinner();
        alert = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        gboyText = new javax.swing.JLabel();
        gboy = new javax.swing.JSpinner();
        genText = new javax.swing.JLabel();
        gen = new javax.swing.JSpinner();
        gsnText = new javax.swing.JLabel();
        gsn = new javax.swing.JSpinner();
        gsalonText = new javax.swing.JLabel();
        gsalon = new javax.swing.JComboBox();
        guncelle = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        gsalonText1 = new javax.swing.JLabel();
        ssalon = new javax.swing.JComboBox();
        guncelle1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        kapat = new javax.swing.JButton();
        anamenu1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 650));

        tab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tab.setName(""); // NOI18N

        filmTab.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Film İsmi :");

        jLabel5.setText("Salon No :");

        jLabel6.setText("Bilet Fiyatı :");

        jLabel7.setText("Seans Ekle :");

        filmKaydet.setText("KAYDET");
        filmKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmKaydetActionPerformed(evt);
            }
        });

        jLabel1.setText("Ekli Seanslar :");

        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ekliseans.setEditable(false);
        ekliseans.setEnabled(false);

        jLabel9.setText("Not : Film kaydetme işlemi 10 saniyeye kadar sürebilir.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(64, 64, 64)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fismi)
                            .addComponent(fsno, 0, 157, Short.MAX_VALUE)
                            .addComponent(bfiyati)))
                    .addComponent(filmKaydet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alert2, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(seansek, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ekliseans)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fismi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fsno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bfiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(seansek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(ekliseans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(alert2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filmKaydet)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Film İsmi :");

        filmSil.setText("FİLMİ SİL");
        filmSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sFilmSil, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filmSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sFilmSil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(filmSil)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout filmTabLayout = new javax.swing.GroupLayout(filmTab);
        filmTab.setLayout(filmTabLayout);
        filmTabLayout.setHorizontalGroup(
            filmTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filmTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        filmTabLayout.setVerticalGroup(
            filmTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmTabLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("Filmler", filmTab);

        seansTab.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        seans_ekle.setText("EKLE");
        seans_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seans_ekleActionPerformed(evt);
            }
        });

        seansText.setText("Seans Saati :");

        seans_saati.setModel(new javax.swing.SpinnerListModel(new String[] {"00:00", "00:15", "00:30", "00:45", "01:00", "01:15", "01:30", "01:45", "02:00", "02:15", "02:30", "02:45", "03:00", "03:15", "03:30", "03:45", "04:00", "04:15", "04:30", "04:45", "05:00", "05:15", "05:30", "05:45", "06:00", "06:15", "06:30", "06:45", "07:00", "07:15", "07:30", "07:45", "08:00", "08:15", "08:30", "08:45", "09:00", "09:15", "09:30", "09:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30", "22:45", "23:00", "23:15", "23:30", "23:45"}));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seans_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(seansText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(seans_saati, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alert1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seansText)
                    .addComponent(seans_saati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(seans_ekle)
                .addGap(43, 43, 43)
                .addComponent(alert1)
                .addGap(45, 45, 45))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sseansText.setText("Seans Saati :");

        seans_sil.setText("SİL");
        seans_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seans_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sseans, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seans_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(sseansText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 168, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(sseans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(sseansText)
                    .addGap(18, 18, 18)
                    .addComponent(seans_sil)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout seansTabLayout = new javax.swing.GroupLayout(seansTab);
        seansTab.setLayout(seansTabLayout);
        seansTabLayout.setHorizontalGroup(
            seansTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seansTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seansTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        seansTabLayout.setVerticalGroup(
            seansTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seansTabLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        tab.addTab("Seanslar", seansTab);

        salonTab.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        kaydet.setText("KAYDET");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        boyText.setText("Boy (Koltuk Sayısı) :");

        boy.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        enText.setText("En (Koltuk Sayısı) :");

        en.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        snText.setText("Salon No :");

        sn.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(snText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sn, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(en))))
                    .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(boyText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snText)
                    .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(en, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boyText)
                    .addComponent(boy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(alert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kaydet)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        gboyText.setText("Boy (Koltuk Sayısı) :");

        genText.setText("En (Koltuk Sayısı) :");

        gsnText.setText("Salon No :");

        gsalonText.setText("Güncellenecek Salon :");

        gsalon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gsalonİtemStateChanged(evt);
            }
        });

        guncelle.setText("GÜNCELLE");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gboyText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gsnText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gsalonText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 52, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gsalon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gsn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gboy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(gen, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gsalonText)
                    .addComponent(gsalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gsnText)
                    .addComponent(gsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genText)
                    .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gboyText)
                    .addComponent(gboy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guncelle)
                .addGap(40, 40, 40))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        gsalonText1.setText("Silinecek Salon :");

        ssalon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ssalonİtemStateChanged(evt);
            }
        });

        guncelle1.setText("SALONU SİL");
        guncelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(gsalonText1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ssalon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(guncelle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gsalonText1)
                    .addComponent(ssalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guncelle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout salonTabLayout = new javax.swing.GroupLayout(salonTab);
        salonTab.setLayout(salonTabLayout);
        salonTabLayout.setHorizontalGroup(
            salonTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salonTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salonTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salonTabLayout.setVerticalGroup(
            salonTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salonTabLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tab.addTab("salonlar", salonTab);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        kapat.setText("Programı Kapat");
        kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapatActionPerformed(evt);
            }
        });

        anamenu1.setText("Ana Menü");
        anamenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(anamenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(anamenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tab.getAccessibleContext().setAccessibleName("filmTab");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapatActionPerformed
        int dialogButton = 0;
    
int dialogResult = JOptionPane.showConfirmDialog (null, "Programı kapatmak istediğinize emin misiniz?","Uyarı",dialogButton);
if(dialogResult == JOptionPane.YES_OPTION){
         System.exit(0);}
        // TODO add your handling code here:
    }//GEN-LAST:event_kapatActionPerformed
    
    private void anamenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenu1ActionPerformed
        this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_anamenu1ActionPerformed

    private void guncelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle1ActionPerformed
        int ssno = (int) ssalon.getSelectedItem();
        String s = "DELETE FROM salon  WHERE no = " + ssno + ";";
        System.out.print(s);
        try {

            preparedStatement = main.conn
            .prepareStatement(s);  // TODO add your handling code here:
            preparedStatement.execute();
            bilgileriGuncelle();
            showMessageDialog(null, "Silme işleme gerçekleştirildi");

        } catch (SQLException|NullPointerException ex) {
            showMessageDialog(null, "Silme İşlemi GERÇEKLEŞTİRİLEMEDİ!!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_guncelle1ActionPerformed

    private void ssalonİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ssalonİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ssalonİtemStateChanged

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        int gsno = (int) gsalon.getSelectedItem();
        String s = "UPDATE salon SET no = "+gsn.getValue()+","+ "dikeyk = "+gboy.getValue() + ","+ "yatayk = "+ gen.getValue() +" WHERE no = " + gsno + ";";
        System.out.print(s);
        try {

            preparedStatement = main.conn
            .prepareStatement(s);  // TODO add your handling code here:
            preparedStatement.execute();
            bilgileriGuncelle();
            showMessageDialog(null, "Güncellemeniz tamamlandı");

        } catch (SQLException|NullPointerException ex) {
            showMessageDialog(null, "Güncelleme YAPILAMADI!!");
        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void gsalonİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gsalonİtemStateChanged
        try {
            // TODO add your handling code here:
            preparedStatement3 = main.conn
            .prepareStatement("SELECT * FROM salon WHERE no = '"+ gsalon.getSelectedItem() + "'");  // TODO add your handling code here:
            resultSet3 = preparedStatement3.executeQuery();
            while(resultSet3.next())
            {
                gsn.setValue(resultSet3.getInt(1));
                gen.setValue(resultSet3.getInt(4));
                gboy.setValue(resultSet3.getInt(3));

            }

        } catch (SQLException|NullPointerException ex) {
            Logger.getLogger(AdminPaneli.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_gsalonİtemStateChanged

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        int salon_no = (int) sn.getValue();
        int salon_en = (int) en.getValue();
        int salon_boy = (int) boy.getValue();
        try {
            preparedStatement = main.conn
            .prepareStatement("INSERT INTO salon ( no, db, dikeyk, yatayk )" +
                "values (?, ?, ?, ?)");
            preparedStatement.setInt(1,salon_no);
            preparedStatement.setBoolean(2,false);
            preparedStatement.setInt(3,salon_boy);
            preparedStatement.setInt(4,salon_en);
            preparedStatement.execute();
            gsalon.removeAllItems();
            bilgileriGuncelle();
            showMessageDialog(null, "Kayıt Yapıldı");

        } catch (SQLException|NullPointerException ex) {
            showMessageDialog(null, "Kayıt YAPILAMADI!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_kaydetActionPerformed

    private void seans_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seans_silActionPerformed

        // TODO add your handling code here:
        try {
            preparedStatement5 = main.conn
            .prepareStatement("DELETE FROM seans WHERE saat = ?");
            preparedStatement5.setString(1, (String) sseans.getSelectedItem());

            preparedStatement5.execute();
            bilgileriGuncelle();
            showMessageDialog(null, "Silme İşlemi Yapıldı");

        } catch (SQLException|NullPointerException ex) {
            showMessageDialog(null, "Silme İşlemi YAPILAMADI!");
        }
    }//GEN-LAST:event_seans_silActionPerformed

    private void seans_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seans_ekleActionPerformed
        try {
            if(seanslar.contains(seans_saati.getValue())){
                showMessageDialog(null, "Eklemeye çalıştığını seans zaten var!");
            }
            else{
                preparedStatement4 = main.conn
                .prepareStatement("INSERT INTO seans ( saat )" +
                    "values (?)");
                preparedStatement4.setString(1, (String) seans_saati.getValue());

                preparedStatement4.execute();

                bilgileriGuncelle();

                showMessageDialog(null, "Ekleme Yapıldı");
            }
        } catch (SQLException|NullPointerException ex) {
            showMessageDialog(null, "Ekleme YAPILAMADI!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_seans_ekleActionPerformed

    private void filmSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmSilActionPerformed

        try {
            preparedStatement17 = main.conn
            .prepareStatement("SELECT sno FROM film WHERE isim = '"+ sFilmSil.getSelectedItem() + "'");  // TODO add your handling code here:
            resultSet17 = preparedStatement17.executeQuery();
            while(resultSet17.next())
            {
                snosil = resultSet17.getInt(1);
            }

            preparedStatement16 = main.conn
            .prepareStatement("DELETE FROM film WHERE sno = ?");
            preparedStatement16.setInt(1, snosil);

            preparedStatement16.execute();

            preparedStatement16 = main.conn
            .prepareStatement("DELETE FROM koltuk WHERE sno = ?");
            preparedStatement16.setInt(1, snosil);
            preparedStatement16.execute();

            preparedStatement16 = main.conn
            .prepareStatement("UPDATE salon SET db = 0 WHERE no ="+snosil);
            preparedStatement16.execute();
            bilgileriGuncelle();
            showMessageDialog(null, "Silme işleme gerçekleştirildi");

        } catch (SQLException|NullPointerException ex) {
            showMessageDialog(null, "Silme İşlemi GERÇEKLEŞTİRİLEMEDİ!!");
            Logger.getLogger(AdminPaneli.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_filmSilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(eklenecekSeansNolari.contains(seansnolari.get(seansek.getSelectedIndex())) | seansKontrolIndex > 10){
            showMessageDialog(null, "Eklemeye çalıştığınız seans, zaten ekli!");
        }else{
            seansKontrolIndex++;

            eklenecekSeansNolari.add(seansnolari.get(seansek.getSelectedIndex()));

            ekliseans.setText(ekliseans.getText()+"  " + (String) seansek.getSelectedItem());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void filmKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmKaydetActionPerformed

        try {
            String a = (String) seansek.getSelectedItem();// TODO add your handling code here:
            if(filmler.contains(fismi.getText())){
                showMessageDialog(null, "Eklemeye çalıştığınız film zaten ekli!");
            }
            else if(fismi.getText().length()== 0 | fsno.getSelectedItem() == null |
                a.length() == 0 |eklenecekSeansNolari.size() == 0){
                showMessageDialog(null, "Gerekli alanları Doldurunuz!");
            }
            else{
                preparedStatement7 = main.conn
                .prepareStatement("INSERT INTO film ( isim, sno, tutar)" +
                    "values (?, ?, ?)");
                preparedStatement7.setString(1, fismi.getText());
                preparedStatement7.setInt(2, (int) fsno.getSelectedItem());
                preparedStatement7.setFloat(3, (float)Float.parseFloat(bfiyati.getText().replace(',', '.')));
                preparedStatement7.execute();

                preparedStatement14 = main.conn
                .prepareStatement("SELECT dikeyk,yatayk from salon WHERE no = "+fsno.getSelectedItem() );
                resultSet14 = preparedStatement14.executeQuery();
                while(resultSet14.next())
                {
                    sboy = resultSet14.getInt(1);
                    sen = resultSet14.getInt(2);

                }

                for(int i = 0;i<eklenecekSeansNolari.size();i++){

                    preparedStatement10 = main.conn.prepareStatement("UPDATE film SET s"+ (i+1) +" = "+
                        eklenecekSeansNolari.get(i)+" WHERE sno = " + (int)fsno.getSelectedItem() + ";");
                    preparedStatement10.execute();

                    for (int d =0;d< sboy; d++ ){
                        for (int j = 1; j<=sen;j++){
                            preparedStatement13 = main.conn
                            .prepareStatement("INSERT INTO koltuk ( kid, sno, seans_no,db)" +
                                "values (?, ?, ?, ?)");
                            preparedStatement13.setString(1, alfabe[d]+j);
                            preparedStatement13.setInt(2, (int) fsno.getSelectedItem());
                            preparedStatement13.setInt(3, eklenecekSeansNolari.get(i));
                            preparedStatement13.setBoolean(4, false);
                            preparedStatement13.execute();

                        }
                    }
                }
                preparedStatement12 = main.conn.prepareStatement("UPDATE salon SET db = 1"
                    +" WHERE no = " + (int)fsno.getSelectedItem() + ";");
                preparedStatement12.execute();

                bilgileriGuncelle();
                eklenecekSeansNolari.clear();
                ekliseans.setText("");
                seansKontrolIndex = 0;
                showMessageDialog(null, "Film Eklendi");

            }
        } catch (SQLException|NullPointerException|NumberFormatException ex) {
            showMessageDialog(null, "Film EKLENEMEDİ!");
            Logger.getLogger(AdminPaneli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filmKaydetActionPerformed
                                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPaneli().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel alert1;
    private javax.swing.JLabel alert2;
    private javax.swing.JButton anamenu1;
    private javax.swing.JTextField bfiyati;
    private javax.swing.JSpinner boy;
    private javax.swing.JLabel boyText;
    private javax.swing.JTextField ekliseans;
    private javax.swing.JSpinner en;
    private javax.swing.JLabel enText;
    private javax.swing.JButton filmKaydet;
    private javax.swing.JButton filmSil;
    private javax.swing.JPanel filmTab;
    private javax.swing.JTextField fismi;
    private javax.swing.JComboBox fsno;
    private javax.swing.JSpinner gboy;
    private javax.swing.JLabel gboyText;
    private javax.swing.JSpinner gen;
    private javax.swing.JLabel genText;
    private javax.swing.JComboBox gsalon;
    private javax.swing.JLabel gsalonText;
    private javax.swing.JLabel gsalonText1;
    private javax.swing.JSpinner gsn;
    private javax.swing.JLabel gsnText;
    private javax.swing.JButton guncelle;
    private javax.swing.JButton guncelle1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton kapat;
    private javax.swing.JButton kaydet;
    private javax.swing.JComboBox sFilmSil;
    private javax.swing.JPanel salonTab;
    private javax.swing.JPanel seansTab;
    private javax.swing.JLabel seansText;
    private javax.swing.JButton seans_ekle;
    private javax.swing.JSpinner seans_saati;
    private javax.swing.JButton seans_sil;
    private javax.swing.JComboBox seansek;
    private javax.swing.JSpinner sn;
    private javax.swing.JLabel snText;
    private javax.swing.JComboBox ssalon;
    private javax.swing.JComboBox sseans;
    private javax.swing.JLabel sseansText;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
